global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'grpc-service'
    static_configs:
      - targets: ['grpc-server:8000']
    scrape_interval: 5s
    metrics_path: /metrics
