apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust-master
        image: locust-grpc:latest
        command: ["locust"]
        args: [
          "--master",
          "--web-host=0.0.0.0",
          "--web-port=8089",
          "--host=http://grpc-service:50051",
          "--locustfile=locustfile.py"
        ]
        ports:
        - containerPort: 8089
          name: web
        - containerPort: 5557
          name: master
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  selector:
    app: locust-master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
    protocol: TCP
  - name: master
    port: 5557
    targetPort: 5557
    protocol: TCP
  type: LoadBalancer
