apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust-worker
spec:
  replicas: 5  # Scale this based on your load testing needs
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust-worker
        image: locust-grpc:latest
        command: ["locust"]
        args: [
          "--worker",
          "--master-host=locust-master",
          "--master-port=5557",
          "--host=http://grpc-service:50051",
          "--locustfile=locustfile.py"
        ]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
